---
# tasks file for digitransit-azure-acs

- name: create AZURE resource group
  shell: az resource group create -n {{resource_group_name}} -l "{{azure_region}}"



- name: create AZURE container service
  shell: "az acs create -n {{acs_name}} \
          -g {{resource_group_name}} \
          -d {{dns_prefix}} \
          --admin-username {{admin_user}} \
          --master-count {{master_nodes}} \
          --agent-count {{agent_nodes}} \
          --orchestrator-type {{orchestrator}} \
          --agent-vm-size {{vm_size}} \
          --generate-ssh-keys"

